site_name: 'WeCube文档中心'
repo_name: 'wecube-platform@GitHub'
repo_url: 'https://github.com/WeBankPartners/wecube-platform'
edit_uri: ''

docs_dir: 'docs'
site_dir: 'site'

nav:
  - '首页': 'index.md'
  - '初识WeCube': 'introduction.md'
  - '安装WeCube':
    - '在私有资源上单机模式安装': 'installation-standalone-mode-on-premises.md'
    - '在私有资源上集群模式安装': 'installation-cluster-mode-on-premises.md'
    - '在私有资源上单机离线模式安装': 'installation-standalone-mode-on-premises-offline.md'
    - '在私有资源上集群离线模式安装': 'installation-cluster-mode-on-premises-offline.md'
    - '在公有云上单机模式安装': 'installation-standalone-mode-on-public-cloud.md'
    - '在公有云上集群模式安装': 'installation-cluster-mode-on-public-cloud.md'
    - '升级WeCube平台': 'installation-upgrade-wecube.md'    
    - 'WeCube安装目录结构': 'installation-directory-structure.md'
  - '上手指引': 
    - '使用上手指引配置进行安装': 'bootcamp-01-installation.md'
    - '探索数据模型与数据记录': 'bootcamp-02-explore-data-model-and-data-records.md'
    - '探索自动化部署插件服务': 'bootcamp-03-explore-plugin-for-deployment.md'
    - '演进数据模型并配置应用': 'bootcamp-04-evolve-data-model-for-application.md'
    - '执行标准化应用部署流程': 'bootcamp-05-execute-sop-for-deployment.md'
    - '完善对主机和应用的监控': 'bootcamp-06-enhance-monitoring.md'
  - '用户手册':
    - '用户角色与画像': 'manual-user-roles-and-profiles.md'
    - '系统参数': 'manual-system-settings.md'
    - '资源管理': 'manual-resource-management.md'
    - '权限管理': 'manual-permission-management.md'
    - '插件注册': 'manual-plugin.md'
    - '任务编排设计': 'manual-orchestration-design.md'
    - '任务编排执行': 'manual-orchestration-execution.md'
    - '任务编排报表': 'manual-orchestration-report.md'
    - '批量执行': 'manual-batch-execution.md'
    - 'CMDB插件功能':
      - 'CMDB模型管理': 'manual-cmdb-model.md'
      - 'CMDB基础数据管理': 'manual-cmdb-enumerations.md'
      - 'CMDB数据权限管理': 'manual-cmdb-data-permission.md'
      - 'CMDB日志查询': 'manual-cmdb-logging.md'
      - 'CMDB数据管理(视图)': 
        - '概要说明': 'manual-cmdb-view-management.md'
        - '应用架构视图': 'manual-cmdb-view-application-architecture.md'
        - '应用部署视图': 'manual-cmdb-view-application-deployment.md'
        - '网络架构视图': 'manual-cmdb-view-network-architecture.md'
        - '网络规划视图': 'manual-cmdb-view-network-planning.md'
        - '资源架构视图': 'manual-cmdb-view-resource-architecture.md'
        - '资源规划视图': 'manual-cmdb-view-resource-planning.md'
      - 'CMDB报表管理':  'manual-cmdb-report.md'
    - '应用物料插件功能':
      - '应用物料管理': 'manual-application-artifacts.md'
    - '监控插件功能':
      - '对象视图': 'manual-open-monitor-object-view.md'
      - '监控配置': 'manual-open-monitor-config.md'
      - '指标设计': 'manual-open-monitor-metrics.md'
      - '告警列表': 'manual-open-monitor-alerting.md'
      - '自定义视图': 'manual-open-monitor-customized-view.md'
    - '高危监测插件功能': 'manual-itsdangerous.md'
    - '远程终端插件功能': 'manual-terminal.md'
    - '容量插件功能': 'manual-capacity.md'
    - '多云管理插件功能': 'manual-terraform.md'
    - '容器管理插件功能': 'manual-kubernetes.md'
    - 'Jenkins集成': 'manual-jenkins.md'
    - 'Taskman插件功能': 'manual-taskman.md'
  - '参考文档':
    - '应用发布规范': 'application-deployment-specification.md'
  - '常见问题': 'faq.md'

extra_css:
  - 'stylesheets/font-awesome.min.css'

theme:
  name: 'material'
  features:
    - instant
  language: 'zh'
  favicon: 'favicon.ico'
  icon:
    logo: 
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - fontawesome_markdown
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search:
      lang:
        - ja
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
# - pdf-export:
#     verbose: true
