site_name: 'WeCube文档中心'
repo_name: 'wecube-platform@GitHub'
repo_url: 'https://github.com/WeBankPartners/wecube-platform'
edit_uri: ''

nav:
  - '首页': 'index.md'
  - '初识WeCube': 'introduction.md'
  - '快速上手': 'tutorial.md'
  - '安装WeCube':
    - '在私有资源上以单机模式安装': 'standalone-mode-on-premises.md'
    - '在公有云上以单机模式安装': 'standalone-mode-on-public-cloud.md'
    - '在公有云上以集群模式安装': 'wip.md'
    - '在Kubernetes集群上安装': 'wip.md'
  - '用户手册':
    - '注册和配置插件': 'plugin.md'
    - '编排配置': 'orchestration-configuration.md'
    - '编排执行': 'orchestration-execution.md'
    - '批量执行': 'batch-execution.md'
  - '参考文档':
    - '应用发布规范': 'application-deployment-specification.md'

docs_dir: 'docs'
site_dir: 'site'

theme:  
  name: 'material'
  language: 'zh'
  favicon: 'images/favicon.ico'

markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - minify:
      minify_html: true
