site_name: 'WeCube文档中心'
repo_name: 'wecube-platform@GitHub'
repo_url: 'https://github.com/WeBankPartners/wecube-platform'
edit_uri: ''

docs_dir: 'docs'
site_dir: 'site'

nav:
  - '首页': 'index.md'
  - '初识WeCube': 'introduction.md'
  - 'What is WeCube?': 'introduction-en.md'
  - '上手指引': 
    - '场景介绍': 'tutorial-scenarios.md'
    - '安装并运行WeCube': 'tutorial-installation.md'
    - '设计并规划您的数据中心': 'tutorial-design-and-plan-idc.md'
    - '创建云上的IT资源': 'tutorial-create-resources.md'
    - '设计您的业务应用系统': 'tutorial-design-business-applications.md'
    - '部署和升级您的业务应用系统': 'tutorial-deploy-business-applications.md'
    - '监测您的数据中心': 'tutorial-monitor.md'
    - '小结': 'tutorial-summary.md'
  - '安装WeCube':
    - '在私有资源上以单机模式安装': 'standalone-mode-on-premises.md'
    - '在公有云上以单机模式安装': 'standalone-mode-on-public-cloud.md'
    - '在公有云上以集群模式安装': 'wip.md'
    - '在Kubernetes集群上安装': 'wip.md'
    - '目录结构': 'directory-structure.md'
  - '用户手册':
    - '注册和配置插件': 'plugin.md'
    - '编排配置': 'orchestration-configuration.md'
    - '编排执行': 'orchestration-execution.md'
    - '批量执行': 'batch-execution.md'
  - '插件':
    - 'WeCMDB': 'plugin-wecmdb.md'
    - 'Open-Monitor': 'plugin-open-monitor.md'
    - 'Saltstack': 'plugin-saltstack.md'
    - 'Qcloud': 'plugin-qcloud.md'
    - 'Artifacts': 'plugin-artifacts.md'
    - 'Service-Management': 'plugin-service-management.md'
    - 'Notification': 'plugin-notification.md'
    - '开发新的插件': 'plugin-development.md'
  - '参考文档':
    - '应用发布规范': 'application-deployment-specification.md'
  - '常见问题': 'faq.md'

theme:
  name: 'material'
  features:
    - instant
  language: 'zh'
  favicon: 'images/favicon.ico'
  icon:
    logo: 
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search:
      lang:
        - ja
  - minify:
      minify_html: true
  # - pdf-export:
  #     verbose: true
