site_name: 'WeCube文档中心'
repo_name: 'wecube-platform@GitHub'
repo_url: 'https://github.com/WeBankPartners/wecube-platform'
edit_uri: ''

docs_dir: 'docs'
site_dir: 'site'

nav:
  - '首页': 'index.md'
  - '初识WeCube': 'introduction.md'
  - '概念解析':
    - 'CMDB模型': 'concept-cmdb-model.md'
    - '插件服务': 'concept-plugin-service.md'
    - '任务编排': 'concept-task-orchestration.md'
#  - 'What is WeCube?': 'introduction-en.md'
  - '安装WeCube':
    - '在私有资源上以单机模式安装': 'standalone-mode-on-premises.md'
    - '在公有云上以单机模式安装': 'standalone-mode-on-public-cloud.md'
    - 'WeCube安装目录结构': 'directory-structure.md'
  - '上手指引': 
    - '场景介绍': 'tutorial-scenarios.md'
    - '安装并运行WeCube': 'tutorial-installation.md'
    - '了解可用的插件': 'tutorial-plugins.md'
    - '设计并规划数据中心': 'tutorial-design-and-plan-idc.md'
    - '创建云上资源': 'tutorial-create-resources.md'
    - '设计业务应用系统': 'tutorial-design-business-applications.md'
    - '部署和升级业务应用系统': 'tutorial-deploy-business-applications.md'
    - '监测数据中心': 'tutorial-monitor.md'
    - '小结': 'tutorial-summary.md'
  - '用户手册':
    - '用户角色与画像': 'manual-user-roles-and-profiles.md'
    - '系统参数': 'manual-system-settings.md'
    - '资源管理': 'manual-resource-management.md'
    - '权限管理': 'manual-permission-management.md'
    - '插件注册': 'manual-plugin.md'
    - 'CMDB模型管理': 'manual-cmdb-model.md'
    - 'CMDB基础数据管理': 'manual-cmdb-enumerations.md'
    - 'CMDB数据权限管理': 'manual-cmdb-data-permission.md'
    - 'CMDB日志查询': 'manual-cmdb-logging.md'
    - 'CMDB资源视图 - 规划设计': 'manual-cmdb-view-resource-planning.md'
    - 'CMDB资源视图 - 资源管理': 'manual-cmdb-view-resource-management.md'
    - 'CMDB应用视图 - 架构设计': 'manual-cmdb-view-application-architecture.md'
    - 'CMDB应用视图 - 架构查询': 'manual-cmdb-view-application-architecture-viewer.md'
    - 'CMDB应用视图 - 部署管理': 'manual-cmdb-view-deployment-management.md'
    - '应用物料管理': 'manual-application-artifacts.md'
    - '任务编排设计': 'manual-orchestration-design.md'
    - '任务编排执行': 'manual-orchestration-execution.md'
    - '批量执行': 'manual-batch-execution.md'
  - '插件':
    - 'WeCMDB': 'plugin-wecmdb.md'
    - 'Open-Monitor': 'plugin-open-monitor.md'
    - 'Saltstack': 'plugin-saltstack.md'
    - 'Qcloud': 'plugin-qcloud.md'
    - 'Artifacts': 'plugin-artifacts.md'
    - 'Service-Management': 'plugin-service-management.md'
    - 'Notification': 'plugin-notification.md'
    - '开发新的插件': 'plugin-development.md'
  - '参考文档':
    - '数据模型表达式解析': 'data-model-expression.md'
    - '应用发布规范': 'application-deployment-specification.md'
  - '常见问题': 'faq.md'

extra_css:
  - 'stylesheets/font-awesome.min.css'

theme:
  name: 'material'
  features:
    - instant
  language: 'zh'
  favicon: 'favicon.ico'
  icon:
    logo: 
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - fontawesome_markdown
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search:
      lang:
        - ja
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
# - pdf-export:
#     verbose: true
