name: Sync to Gitee
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  run:
    name: Sync WeBankPartners@GitHub repos to WeBankPartners@Gitee with force push (git push -f)
    runs-on: ubuntu-latest
    steps:
    - name: Sync using kanetz/hub-mirror-action@master (forked from Yikun/hub-mirror-action)
      uses: kanetz/hub-mirror-action@master
      with:
        src: github/WeBankPartners
        dst: gitee/WeBankPartners
        account_type: org
        dst_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_API_TOKEN }}
        force_update: true
